[package]
name = "iota-wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = [ "cdylib", "staticlib" ]      # Creates dynamic lib

[dependencies]
fern-logger = { version = "0.5.0", default-features = false }
futures =  { version = "0.3.23", default-features = false }
iota-wallet = { path = "../../", features = ["message_interface", "events"] }
log = { version = "0.4.17", default-features = false }
once_cell = { version = "1.13.1", default-features = false }
serde = { version = "1.0.143", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.83", default-features = false }
tokio = { version = "1.20.1", default-features = false}
